/*
 * uw_hal_config.h
 *
 *  Created on: Mar 22, 2016
 *      Author: usevolt
 */

#ifndef UW_HAL_CONFIG_H_
#define UW_HAL_CONFIG_H_


/**** USER CONFIGURATIONS ****/


/* Defines the build target MCU family
 *
 * NOTE: Only one target MCU should be defined! */
#define CONFIG_TARGET_LPC11C14				1
#define CONFIG_TARGET_LPC1785				0


// workaround for eclipse makefile defined symbol bug where
// symbols are parsed without their values.
#if defined(LEFT)
#undef LEFT
#define LEFT 1
#elif defined(RIGHT)
#undef RIGHT
#define RIGHT 1
#endif



#define CONFIG_LOG_ERRORS							1
#define CONFIG_INFORMATIVE_ERRORS					0



/* Enables FreeRTOS implementation.
 * Note: RTOS is not available for Cortex-M0 based
 * MCU's and thus should be disabled when compiling
 * for them.*/
#define CONFIG_RTOS									1
#define CONFIG_RTOS_HEAP_SIZE						3000




#define CONFIG_CAN									1
#define CONFIG_CAN1									1
#define CONFIG_CAN_LOG								0
#define CONFIG_CAN_ERROR_LOG						0
#define CONFIG_CAN1_RX_BUFFER_SIZE					4
#define CONFIG_CAN1_TX_BUFFER_SIZE					4
#define CONFIG_CAN1_BAUDRATE						250000



#define CONFIG_CANOPEN								1
#define CONFIG_CANOPEN_LOG							0
#define CONFIG_CANOPEN_RXPDO_COUNT					0
#define CONFIG_CANOPEN_TXPDO_COUNT					3
#define CONFIG_CANOPEN_PDO_MAPPING_COUNT 			8
#define CONFIG_CANOPEN_PREDEFINED_ERROR_SIZE		4
#define CONFIG_CANOPEN_DEVICE_TYPE_INDEX			0x1000
#define CONFIG_CANOPEN_ERROR_REGISTER_INDEX			0
#define CONFIG_CANOPEN_PREDEFINED_ERROR_FIELD_INDEX	0
#define CONFIG_CANOPEN_NODEID_INDEX					0x100B
#define CONFIG_CANOPEN_STORE_PARAMS_INDEX			0x1010
#define CONFIG_CANOPEN_RESTORE_PARAMS_INDEX			0x1011
#define CONFIG_CANOPEN_HEARTBEAT_INDEX				0x1017
#define CONFIG_CANOPEN_IDENTITY_INDEX				0
#define CONFIG_CANOPEN_TXPDO_COM_INDEX				0x1800
#define CONFIG_CANOPEN_TXPDO_MAP_INDEX				0x1A00
#define CONFIG_CANOPEN_RXPDO_COM_INDEX				0x1400
#define CONFIG_CANOPEN_RXPDO_MAP_INDEX				0x1600

#if LEFT
#define CONFIG_CANOPEN_DEFAULT_NODE_ID				0x3
#elif RIGHT
#define CONFIG_CANOPEN_DEFAULT_NODE_ID				0x4
#endif
#define CONFIG_CANOPEN_DEFAULT_HEARTBEAT_TIME		1000
#define CONFIG_CANOPEN_DEVICE_TYPE					0
#define CONFIG_CANOPEN_VENDOR_ID					0
#define CONFIG_CANOPEN_PRODUCT_CODE					0x00A60000
#define CONFIG_CANOPEN_REVISION_CODE				2

#define CONFIG_CANOPEN_TXPDO1_ID					(CANOPEN_TXPDO1_ID | CONFIG_CANOPEN_DEFAULT_NODE_ID)
#define CONFIG_CANOPEN_TXPDO1_TRANSMISSION_TYPE		CANOPEN_PDO_TRANSMISSION_ASYNC
#define CONFIG_CANOPEN_TXPDO1_EVENT_TIMER			20
#define CONFIG_CANOPEN_TXPDO1_MAPPING1_MAIN_INDEX	0x2100
#define CONFIG_CANOPEN_TXPDO1_MAPPING1_SUB_INDEX	1
#define CONFIG_CANOPEN_TXPDO1_MAPPING1_LEN			1
#define CONFIG_CANOPEN_TXPDO1_MAPPING2_MAIN_INDEX	0x2100
#define CONFIG_CANOPEN_TXPDO1_MAPPING2_SUB_INDEX	2
#define CONFIG_CANOPEN_TXPDO1_MAPPING2_LEN			1
#define CONFIG_CANOPEN_TXPDO1_MAPPING3_MAIN_INDEX	0x2101
#define CONFIG_CANOPEN_TXPDO1_MAPPING3_SUB_INDEX	1
#define CONFIG_CANOPEN_TXPDO1_MAPPING3_LEN			1
#define CONFIG_CANOPEN_TXPDO1_MAPPING4_MAIN_INDEX	0x2101
#define CONFIG_CANOPEN_TXPDO1_MAPPING4_SUB_INDEX	2
#define CONFIG_CANOPEN_TXPDO1_MAPPING4_LEN			1
#define CONFIG_CANOPEN_TXPDO1_MAPPING5_MAIN_INDEX	0x2102
#define CONFIG_CANOPEN_TXPDO1_MAPPING5_SUB_INDEX	1
#define CONFIG_CANOPEN_TXPDO1_MAPPING5_LEN			1
#define CONFIG_CANOPEN_TXPDO1_MAPPING6_MAIN_INDEX	0x2102
#define CONFIG_CANOPEN_TXPDO1_MAPPING6_SUB_INDEX	2
#define CONFIG_CANOPEN_TXPDO1_MAPPING6_LEN			1
#define CONFIG_CANOPEN_TXPDO1_MAPPING7_MAIN_INDEX	0x2103
#define CONFIG_CANOPEN_TXPDO1_MAPPING7_SUB_INDEX	1
#define CONFIG_CANOPEN_TXPDO1_MAPPING7_LEN			1
#define CONFIG_CANOPEN_TXPDO1_MAPPING8_MAIN_INDEX	0x2103
#define CONFIG_CANOPEN_TXPDO1_MAPPING8_SUB_INDEX	2
#define CONFIG_CANOPEN_TXPDO1_MAPPING8_LEN			1


#define CONFIG_CANOPEN_TXPDO2_ID					(CANOPEN_TXPDO2_ID | CONFIG_CANOPEN_DEFAULT_NODE_ID)
#define CONFIG_CANOPEN_TXPDO2_TRANSMISSION_TYPE		CANOPEN_PDO_TRANSMISSION_ASYNC
#define CONFIG_CANOPEN_TXPDO2_EVENT_TIMER			20
#define CONFIG_CANOPEN_TXPDO2_MAPPING1_MAIN_INDEX	0x2001
#define CONFIG_CANOPEN_TXPDO2_MAPPING1_SUB_INDEX	1
#define CONFIG_CANOPEN_TXPDO2_MAPPING1_LEN			1
#define CONFIG_CANOPEN_TXPDO2_MAPPING2_MAIN_INDEX	0x2002
#define CONFIG_CANOPEN_TXPDO2_MAPPING2_SUB_INDEX	1
#define CONFIG_CANOPEN_TXPDO2_MAPPING2_LEN			1
#define CONFIG_CANOPEN_TXPDO2_MAPPING3_MAIN_INDEX	0x2003
#define CONFIG_CANOPEN_TXPDO2_MAPPING3_SUB_INDEX	1
#define CONFIG_CANOPEN_TXPDO2_MAPPING3_LEN			1
#define CONFIG_CANOPEN_TXPDO2_MAPPING4_MAIN_INDEX	0x2004
#define CONFIG_CANOPEN_TXPDO2_MAPPING4_SUB_INDEX	1
#define CONFIG_CANOPEN_TXPDO2_MAPPING4_LEN			1
#define CONFIG_CANOPEN_TXPDO2_MAPPING5_MAIN_INDEX	0x2005
#define CONFIG_CANOPEN_TXPDO2_MAPPING5_SUB_INDEX	1
#define CONFIG_CANOPEN_TXPDO2_MAPPING5_LEN			1
#define CONFIG_CANOPEN_TXPDO2_MAPPING6_MAIN_INDEX	0x2006
#define CONFIG_CANOPEN_TXPDO2_MAPPING6_SUB_INDEX	1
#define CONFIG_CANOPEN_TXPDO2_MAPPING6_LEN			1
#define CONFIG_CANOPEN_TXPDO2_MAPPING7_MAIN_INDEX	0x2007
#define CONFIG_CANOPEN_TXPDO2_MAPPING7_SUB_INDEX	1
#define CONFIG_CANOPEN_TXPDO2_MAPPING7_LEN			1
#define CONFIG_CANOPEN_TXPDO2_MAPPING8_MAIN_INDEX	0x2008
#define CONFIG_CANOPEN_TXPDO2_MAPPING8_SUB_INDEX	1
#define CONFIG_CANOPEN_TXPDO2_MAPPING8_LEN			1


#define CONFIG_CANOPEN_TXPDO3_ID					(CANOPEN_TXPDO3_ID | CONFIG_CANOPEN_DEFAULT_NODE_ID)
#define CONFIG_CANOPEN_TXPDO3_TRANSMISSION_TYPE		CANOPEN_PDO_TRANSMISSION_ASYNC
#define CONFIG_CANOPEN_TXPDO3_EVENT_TIMER			20
#define CONFIG_CANOPEN_TXPDO3_MAPPING1_MAIN_INDEX	0x2009
#define CONFIG_CANOPEN_TXPDO3_MAPPING1_SUB_INDEX	1
#define CONFIG_CANOPEN_TXPDO3_MAPPING1_LEN			1
#define CONFIG_CANOPEN_TXPDO3_MAPPING2_MAIN_INDEX	0x200A
#define CONFIG_CANOPEN_TXPDO3_MAPPING2_SUB_INDEX	1
#define CONFIG_CANOPEN_TXPDO3_MAPPING2_LEN			1
#define CONFIG_CANOPEN_TXPDO3_MAPPING3_MAIN_INDEX	0
#define CONFIG_CANOPEN_TXPDO3_MAPPING3_SUB_INDEX	0
#define CONFIG_CANOPEN_TXPDO3_MAPPING3_LEN			0
#define CONFIG_CANOPEN_TXPDO3_MAPPING4_MAIN_INDEX	0
#define CONFIG_CANOPEN_TXPDO3_MAPPING4_SUB_INDEX	0
#define CONFIG_CANOPEN_TXPDO3_MAPPING4_LEN			0
#define CONFIG_CANOPEN_TXPDO3_MAPPING5_MAIN_INDEX	0
#define CONFIG_CANOPEN_TXPDO3_MAPPING5_SUB_INDEX	0
#define CONFIG_CANOPEN_TXPDO3_MAPPING5_LEN			0
#define CONFIG_CANOPEN_TXPDO3_MAPPING6_MAIN_INDEX	0
#define CONFIG_CANOPEN_TXPDO3_MAPPING6_SUB_INDEX	0
#define CONFIG_CANOPEN_TXPDO3_MAPPING6_LEN			0
#define CONFIG_CANOPEN_TXPDO3_MAPPING7_MAIN_INDEX	0
#define CONFIG_CANOPEN_TXPDO3_MAPPING7_SUB_INDEX	0
#define CONFIG_CANOPEN_TXPDO3_MAPPING7_LEN			0
#define CONFIG_CANOPEN_TXPDO3_MAPPING8_MAIN_INDEX	0
#define CONFIG_CANOPEN_TXPDO3_MAPPING8_SUB_INDEX	0
#define CONFIG_CANOPEN_TXPDO3_MAPPING8_LEN			0






#define CONFIG_NON_VOLATILE_MEMORY			1






/* Enables the UART modules.
 * Note: Refer to the MCU's datasheet for available UARTs.
 */
#define CONFIG_UART0					1
#define CONFIG_UART0_RX_BUFFER_SIZE		8
#define CONFIG_UART0_BAUDRATE			115200
#define CONFIG_UART0_DATA_8_BYTES		1
#define CONFIG_UART0_DATA_7_BYTES		0
#define CONFIG_UART0_DATA_6_BYTES		0
#define CONFIG_UART0_DATA_5_BYTES		0
#define CONFIG_UART0_PARITY_NONE		1
#define CONFIG_UART0_PARITY_ODD			0
#define CONFIG_UART0_PARITY_EVEN		0
#define CONFIG_UART0_STOP_BITS_1		1
#define CONFIG_UART0_STOP_BITS_2		0






#define CONFIG_TERMINAL_BUFFER_SIZE		200
#define CONFIG_TERMINAL_ARG_COUNT		4
#define CONFIG_TERMINAL_INSTRUCTIONS	0
#define CONFIG_TERMINAL_CAN				1
#define CONFIG_TERMINAL_UART			1






#define CONFIG_ADC						1
#define CONFIG_ADC_CHANNEL0				1
#define CONFIG_ADC_CHANNEL1				1
#define CONFIG_ADC_CHANNEL2				1
#define CONFIG_ADC_CHANNEL3				0
#define CONFIG_ADC_CHANNEL4				0
#define CONFIG_ADC_CHANNEL5				0
#define CONFIG_ADC_CHANNEL6				0
#define CONFIG_ADC_CHANNEL7				0



#define CONFIG_WDT						1
#define CONFIG_WDT_CYCLE_S				5


#define CONFIG_TIMER0					0
#define CONFIG_PWM0						0
#define CONFIG_COUNTER0					0
#define CONFIG_TIMER1					0
#define CONFIG_PWM1						0
#define CONFIG_COUNTER1					0
#define CONFIG_TIMER2					0
#define CONFIG_PWM2						0
#define CONFIG_COUNTER2					0
#define CONFIG_TIMER3					0
#define CONFIG_PWM3						0
#define CONFIG_COUNTER3					0






/* Enables all GPIO pins from specific ports.
 * GPIO pin functions cannot be used for specific port pins
 * if the port is not enabled with these or
 * pin is not enabled with configurations below.
 *
 * Refer to the MCU datasheet for PORTs available.*/
#define CONFIG_PORT0					0
#define CONFIG_PORT1					0
#define CONFIG_PORT2					0
#define CONFIG_PORT3					0
#define CONFIG_PORT4					0
#define CONFIG_PORT5					0




/**** END OF USER CONFIGURATIONS ****/




#endif /* UW_HAL_CONFIG_H_ */
